### ISSUE TITLE
Server needs to generate keys

### ISSUE THREAD

**Issue by technosophos** [deislabs/bindle#104]
The server should generate a `host` key (alternately, the `bindle create-key` command could just create `host` keys for you). This should be stored in the bindle config dir.

See #103

**Comment by technosophos** [comment]
*Update:* `bindle create-key` needs to support `-r host` to allow the host role. Otherwise, you need to edit the key file directly.

**Comment by thomastaylor312** [comment]
This feature now exists and keys are created on startup
