### ISSUE TITLE
Improve server errors

### ISSUE THREAD

**Issue by itowlson** [deislabs/bindle#113]
For example, while testing Create Invoice:

* I screwed up serialisation and had it sending `[parcels]` instead of `[parcel]`.  Got a 400 and no hint as to why.
* I forgot that a successful test would create the bindle, and so was at a loss when running the test again gave me a 400.

In both cases, a clear error message would have helped.

Also, in the second case, consider 409 Conflict instead of 400 Bad Request.  It was a perfectly good request, just the resource already existed and couldn't be overwritten.

(If Bindle is sending a clear error message and Axios is throwing it away on the client, then feel free to close this issue.)

**Comment by technosophos** [comment]
I verified that if the error is that the file exists, it currently sends a 409, not a 400. I am checking to see if there is another cause of a 400 if the only problem is that the invoice already existed.

**Comment by technosophos** [comment]
Yeah, I see what you mean. Lots of the response codes that are coming back from the server just don't make sense. I am, for example, getting a 404 when I push an invoice... and zero reason why that's a 404 instead of a 400, 409, or 500. Furthermore, nothing is logged on the server, either.

**Comment by technosophos** [comment]
So at least part of my problem was that I was using the wrong `BINDLE_SERVER_URL` (See #126). Will keep hunting for error issues and see if I can fix the problems reported here.

**Comment by thomastaylor312** [comment]
I think we've improved this quite a bit at this point, correct? Is there any outstanding work that needs to be completed to mark this as complete?

**Comment by thomastaylor312** [comment]
Going ahead and closing this. Other error improvements have been captured in other issues
