### ISSUE TITLE
Accept charset in Content-Type header

### ISSUE THREAD

**Issue by itowlson** [deislabs/bindle#131]
When creating an invoice, if you send a Content-Type of `application/toml; charset=...`, the server rejects it with 400 Bad Request, because it tries to exactly match the string `application/toml` and the additional clause confuses it.  However this is allowed by the HTTP spec and is sent by default by at least the .NET HttpClient/StringContent class.  The server should accept the charset declaration.

**Comment by technosophos** [comment]
I worked for a while on this, but got nowhere. I think it is a matter of writing a custom filter.
