### ISSUE TITLE
[Discussion] Do not return Accepted for invoice creation

### ISSUE THREAD

**Issue by itowlson** [deislabs/bindle#134]
When you POST an invoice, the invoice resource is created immediately and is available immediately.  This maps to the HTTP 201 Created status code.

However, if there are any parcels not currently uploaded, we currently return HTTP 202 Accepted.  The intended usage of this is for resources that are created asynchronously and may not be available immediately.  This is misleading as the invoice has definitely been created, but not all of its parcels are available.

Should we return Created for this case too?  We would probably need to overload the response body, though, to say if any parcels are unavailable, which is a bit iffy.  Or are we okay with the use of the async creation status?

**Comment by technosophos** [comment]
I believe this is correct behavior, per https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202

While the current version of Bindle is not yet so, the idea is that the invoice should be accepted (with 202), but cannot be fetched until after all the parcels are uploaded. A 202 always returns a list of parcels that need to be uploaded (while a 201 does not).

**Comment by itowlson** [comment]
If that's the long term intention then Accepted is fine.  Thanks!  Closing.
