### ISSUE TITLE
Discussion: `push` command names

### ISSUE THREAD

**Issue by itowlson** [deislabs/bindle#160]
We currently have the following commands:

```
push              push a bindle and all its parcels to the server
push-file         push an arbitrary file as a parcel to the server
push-invoice      push an invoice file to the server
```

The `push` name is so general it makes it easy to mistake for the other commands.  I wonder if it is worth renaming it, e.g. to `push-id` or `push-bindle`.  Perhaps `push-file` might be clearer as `push-parcel` too?

Alternatively we could keep `push` but make it cleverer:

- If the argument looks like a bindle id, and that bindle id exists locally, push the bindle
- If the argument is named `invoice.toml`, push it as an invoice
- Otherwise, push it as a parcel

This adds complexity and possible unpredictability though!

We could also restructure the `push` commands as subcommands a la `bindle push invoice -f invoice.toml`.  This would allow a user to type `bindle push` and get help text specifically on the various push options.

What do folks think?  Would any of these be improvements or is what we have fine?

**Comment by thomastaylor312** [comment]
I think what we have is fairly well documented in the help text so I am not sure how much confusion there is/isn't around it. If we were to change though I actually really like the subcommand idea. Think that is cleaner and more explicit than the other options IMO.

**Comment by technosophos** [comment]
i think that in general I am opposed to (a) making the "push all the things" command more verbose than just `push`, and (b) doing "magic" that could result in really peculiar side effects if an argument looks like something other than what it is.

It makes a lot of sense that `bindle push` pushes everything, and if you want to push just some things you would use more specific commands.

That said, I would be inclined to provide better help/feedback (which we have been working on).

**Comment by thomastaylor312** [comment]
Was there any more discussion to be had here?

**Comment by thomastaylor312** [comment]
Going to close this. Please feel free to reopen if you want to continue the discussion @itowlson!
