### ISSUE TITLE
Inconsistent client/server flag and environment variable names

### ISSUE THREAD

**Issue by adamreese** [deislabs/bindle#181]
For bindle directory:
client: --bindle-dir and BINDLE_DIR
server: --directory and BINDLE_DIRECTORY

For server url:
client: --server, -s and BINDLE_URL
server: --address, -i and BINDLE_IP_ADDRESS_PORT

**Comment by adamreese** [comment]
I remembered that BINDLE_URL and BINDLE_IP_ADDRESS_PORT are different things.

`BINDLE_URL=${BINDLE_IP_ADDRESS_PORT}/v1`

**Comment by technosophos** [comment]
It's actually BINDLE_URL=${PROTO}://${BINDLE_IP_ADDRESS_PORT}/v1, where PROTO is http or https.
