### ISSUE TITLE
curl https:// works fine, but `bindle search` does not

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/bindle#202]
So I have an interesting setup where I have both bindle and nginx set up with the same TLS certificate.

When TLS is disabled, `bindle` can reach the bindle server and query its search endpoint. However when TLS is enabled, only `curl` can query the search endpoint, but `bindle` returns the error "frame with invalid size".

Here's the nginx config without TLS (note that certain lines are commented out, and the `proxy_pass` is forwarding to `http`:

```
# BINDLE
server {
        listen      8080 http2;
        server_name bindle.f1sh.ca;
        server_name_in_redirect off;
        port_in_redirect off;
        #ssl_certificate /etc/nginx/ssl/bindle.crt;
        #ssl_certificate_key /etc/nginx/ssl/bindle.key;
        #ssl on;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_redirect off;
                proxy_pass http://10.0.0.4:8080;
                client_max_body_size 128m;
        }
}
```

`/usr/local/bin/bindle-server --config-path /usr/local/etc/bindle/bindle.toml --directory /usr/local/lib/bindle --keyring /usr/local/etc/bindle/keyring.toml --signing-keys /usr/local/etc/bindle/signing_keys.toml`.

```
$ bindle --server http://bindle.f1sh.ca:8080/v1 search
query = ""
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []
```

With TLS (tls-related config is uncommented, and `proxy_pass` is now passing via the https scheme):

```
# BINDLE
server {
        listen      8080 http2;
        server_name bindle.f1sh.ca;
        server_name_in_redirect off;
        port_in_redirect off;
        ssl_certificate /etc/nginx/ssl/bindle.crt;
        ssl_certificate_key /etc/nginx/ssl/bindle.key;
        ssl on;
        location / {
                proxy_set_header Host $host;
                proxy_set_header X-Forwarded-For $remote_addr;
                proxy_redirect off;
                proxy_pass https://10.0.0.4:8080;
                client_max_body_size 128m;
        }
}
```

`/usr/local/bin/bindle-server --config-path /usr/local/etc/bindle/bindle.toml --directory /usr/local/lib/bindle --keyring /usr/local/etc/bindle/keyring.toml --signing-keys /usr/local/etc/bindle/signing_keys.toml --tls-cert /usr/local/etc/bindle/bindle.crt --tls-key /usr/local/etc/bindle/bindle.key`

```
$ bindle --server https://bindle.f1sh.ca:8080/v1 search
Error creating request

Error trace:
	1: error sending request for url (https://bindle.f1sh.ca:8080/v1/_q): http2 error: protocol error: frame with invalid size
	2: http2 error: protocol error: frame with invalid size
	3: protocol error: frame with invalid size
```

But with `curl`:

```
$ curl https://bindle.f1sh.ca:8080/v1/_q
query = ""
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []
```

This is a self-signed certificate... Not sure if that plays into this. But it was added to my ca-cert chain and both curl and bindle trust it.

**Comment by itowlson** [comment]
This may relate to https://github.com/deislabs/bindle/pull/147.  `curl` negotiates HTTP/2 by default, but `bindle` assumes it.  Try it with the curl HTTP2 prior knowledge flag and see if it fails?

**Comment by bacongobbler** [comment]
Like this?

```
><> curl --http2-prior-knowledge https://bindle.f1sh.ca:8080/v1/_q
query = ""
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []
```

**Comment by itowlson** [comment]
I was just recalling that I got a similar error when I had a proxy in front of Bindle - curl worked but the Bindle client library didn't.  I added the option to negotiate and it started working.  But I guess from your curl command that it's not that.  *grin*  _homer backing into hedge.gif_

**Comment by bacongobbler** [comment]
It's a good idea... Let me try enabling that flag in bindle and see how far I get.

**Comment by bacongobbler** [comment]
Huh... setting 

https://github.com/deislabs/bindle/blob/ab5f5a14831edbcf357c74b4985c8e57ab1e0509/src/client/mod.rs#L57

to `false` and recompiling worked. How odd...

```
><> ./target/release/bindle --server https://bindle.f1sh.ca:8080/v1 search
query = ""
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []
```

**Comment by bacongobbler** [comment]
From [curl's documentation](https://github.com/curl/curl/blob/fbf26594e38ebf6e8b0f0e0583fbb7dd833720a4/docs/cmdline-opts/http2-prior-knowledge.d#L10-L13):

> Tells curl to issue its non-TLS HTTP requests using HTTP/2 without HTTP/1.1
Upgrade. It requires prior knowledge that the server supports HTTP/2 straight
away. HTTPS requests will still do HTTP/2 the standard way with negotiated
protocol version in the TLS handshake.

So I'm not sure why disabling that flag would allow bindle to work in this situation. This flag should not affect HTTPS requests if I'm reading the docs correctly.

Perhaps it's a bug in reqwest's implementation of the `--http2-prior-knowledge` flag?

**Comment by bacongobbler** [comment]
Possible relevant issue: https://github.com/seanmonstar/reqwest/issues/857
