### ISSUE TITLE
human-readable `bindle search`?

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/bindle#208]
The output of `bindle search` is difficult to read as it's all in TOML mixed in with plain text (the first few lines). Is it possible to add an `--output` flag to display the results in a more accessible format?

```
><> bindle --server https://*****/v1 search -q fileserver
query = "fileserver"
strict = true
offset = 0
limit = 50
total = 2
more = false
yanked = false

[[invoices]]
bindleVersion = "1.0.0"

[invoices.bindle]
name = "fileserver"
version = "0.4.0"
description = "Provides static file serving for Wagi"

[[invoices.parcel]]
[invoices.parcel.label]
sha256 = "c5849b15ee3be896115835bd285e68f55a160c7b7823b9f538aa5cc5f055acb5"
mediaType = "application/wasm"
name = "fileserver.gr.wasm"
size = 191177
[invoices.parcel.label.feature.wagi]
file = "false"
route = "/static/..."

[invoices.parcel.conditions]
requires = ["fileserver.gr.wasm-files"]

[[invoices.parcel]]
[invoices.parcel.label]
sha256 = "c5849b15ee3be896115835bd285e68f55a160c7b7823b9f538aa5cc5f055acb5"
mediaType = "application/wasm"
name = "fileserver.gr.wasm"
size = 191177

...
```

Part of the reason is that the output for two invoices returns 153 lines of output. I'd imagine this would balloon if I uploaded more development builds to bindle-server.

```
><> bindle --server https://*****/v1 search -q fileserver | wc -l
153
```

**Comment by itowlson** [comment]
A list option to just list the matching invoice IDs would be sweet.

**Comment by bacongobbler** [comment]
Suggested change would be to use `bindle search` display just the names that were found. If users wanted to further inspect the parcel information they could either pass an `--output toml` flag or perhaps make it a separate command like `bindle inspect`.

Suggested output change:

```
><> bindle --server **** search --query fileserver
fileserver/0.4.0
fileserver/0.4.0-bacongobbler-2021.08.04.09.48.24.188
```

**Comment by technosophos** [comment]
Technically speaking, the entire output of search is TOML. And we could easily support JSON and other formats... so I think this proposal in the previous comment is a good idea.
