### ISSUE TITLE
Auth token error: `Invalid TOML: expected an equals, found eof at line 1 column 41`

### ISSUE THREAD

**Issue by itowlson** [deislabs/bindle#228]
Using Bindle 0.5.0:

```
✔ ~/github/bindle [main|✔]
16:20 $ cargo run --bin bindle --features="cli" -- --server $BINDLE_URL search
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/bindle --server 'https://bindle.deislabs.io/v1' search`
Invalid TOML

Error trace:
        1: expected an equals, found eof at line 1 column 41
```

I tried running a local server and got the same issue.  Not sure what bindles existed on the local server (probably none, because it uses the database instead of the filesystem now?).

**Comment by itowlson** [comment]
I (apparently successfully) pushed a "toast demo" bindle to my local server and it gave the same error.

I tried passing `-q itowlson` which should have matched the pushed bindle, but got the same error.

**Comment by thomastaylor312** [comment]
Running off of main, I cannot duplicate the issue. I created a few invoices and then ran this:

```
.\target\debug\bindle.exe search
enterprise.com/cargobay/1.0.0:  The cargo bay manifest
enterprise.com/warpcore/1.0.0:  Warp core components
=== Showing results 1 to 2 of 2 (limit: 50)
```

I also tried with a query:

```
.\target\debug\bindle.exe search -q warpcore
enterprise.com/warpcore/1.0.0:  Warp core components
=== Showing results 1 to 1 of 1 (limit: 50)
```

**Comment by itowlson** [comment]
The issue occurs when there is an existing `~/.config/bindle/.token` file that is not in the format Bindle expects.  (In my case, it was an old skool GitHub token blob.)  This is unlikely to happen in the real world, so no need to accommodate it gracefully, but the message could say which file was invalid TOML so the user could go "but I'm not using that" and delete it.
