### ISSUE TITLE
Add a `bindle clean` subcommand

### ISSUE THREAD

**Issue by thomastaylor312** [deislabs/bindle#280]
Right now the bindle cli uses the `DumbCache` to store files locally. There are many reasons to want to clear this cache, particularly if you are testing bindle locally and nuke your bindle server's store of data. 

We should add a `clean` subcommand to the bindle CLI that removes all cached bindles

**Comment by VishnuJin** [comment]
@thomastaylor312 I would like to work on this issue !!

**Comment by thomastaylor312** [comment]
Awesome! Please feel free to ping me when you open a PR
