### ISSUE TITLE
CI: publish release blob-store upload error

### ISSUE THREAD

**Issue by vdice** [deislabs/bindle#354]
Recent runs of the release.yml show a failed 'publish release assets' task, eg https://github.com/deislabs/bindle/actions/runs/3339336662/jobs/5528370148

This appears to fail on our use of the [bacongobbler/azure-blob-storage-upload](https://github.com/bacongobbler/azure-blob-storage-upload), so the bug may lie there or in our usage.  cc @bacongobbler 

Pertinent error details are:
```
ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: argument _subcommand: conflicting subparser: upload-batch
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/commands/__init__.py", line 565, in execute
    self.parser.load_command_table(self.commands_loader)
  File "/usr/local/lib/python3.11/site-packages/azure/cli/core/parser.py", line 100, in load_command_table
    command_parser = subparser.add_parser(command_verb,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/argparse.py", line 1185, in add_parser
    raise ArgumentError(self, _('conflicting subparser: %s') % name)
argparse.ArgumentError: argument _subcommand: conflicting subparser: upload-batch
```

**Comment by thomastaylor312** [comment]
It actually looks like it is related to this issue (and other issues linked to it) https://github.com/Azure/azure-cli/issues/23015. There is an incompatibility with python 3.11 with an open PR to fix. We also could set the python version to be python 3.10 instead inside of our pipeline

**Comment by bacongobbler** [comment]
A fix has been applied to main. I have yet to release a 2.0.1 for blob-storage-upload, though.

**Comment by thomastaylor312** [comment]
@bacongobbler Would you mind coming back here and bumping the version in our pipeline once you have some time to release the new version of blob-storage-upload?
