### ISSUE TITLE
Invoice/Parcel signing

### ISSUE THREAD

**Issue by technosophos** [deislabs/bindle#62]
The signing needs to be implemented on bindles and parcels.

**Comment by thomastaylor312** [comment]
Was this closed by #76?

**Comment by technosophos** [comment]
I need to revisit the parcels to see if anything does need to be signed given our re-architecture. Then we have to actually implement the signing in the CLI and server.

**Comment by technosophos** [comment]
Oh! I just saw #89, which covers the remaining tasks. So I will close this one.
