### ISSUE TITLE
Better concurrent streaming

### ISSUE THREAD

**Issue by technosophos** [deislabs/bindle#65]
What are ways that we can improve the concurrency by which Bindle clients can fetch parcels?

In the original proposal we had an HTTP/3 method mapped out where a single session could be used to fetch the invoice, then fetch all of the necessary parcels in parallel. I suspect this could be at least partially done in HTTP/2.

**Comment by thomastaylor312** [comment]
Is this something we have to build in? I don't know if we have session reuse (I know for sure that `reqwest` keeps the socket open after use), but I don't know if we can do that outside of HTTP/3. I also have the CLI logic set up such that each parcel fetch is its own concurrent task

**Comment by thomastaylor312** [comment]
@technosophos I think we decided we were good to go on this right? The Rust client is set to http/2 only and so it should multiplex over the the same stream when fetching multiple parcels, correct?

**Comment by technosophos** [comment]
Yes. I will mark this as closed. Good catch,
