### ISSUE TITLE
Key management endpoint

### ISSUE THREAD

**Issue by technosophos** [deislabs/bindle#66]
Do we want to provide an endpoint for _fetching_ the public keys that Bindle knows about? /cc @radu-matei

**Comment by technosophos** [comment]
I think that for right now, we have decided not to do this on Bindle itself. Bindle will have a keyring file located in a well-documented location (See #87). So we would just leave it to the user or to other tooling to manage that file for now.

**Comment by thomastaylor312** [comment]
Between the new CLI functionality for managing keychains and the proposal at #300 that supersedes this, I think we can go ahead ad close it
