### ISSUE TITLE
Configuration Files and Config Dir

### ISSUE THREAD

**Issue by technosophos** [deislabs/bindle#87]
Bindle should have a configuration directory with the following files:

- server.toml: Basic configuration, like port, hostname, etc.
- keyring.toml: Public keyrings (possibly temporary)
- signing.key: mode 600 file with just the secret key used for signing packages

The configuration directory should default to a well-known location (either $XDG_CONFIG_DIR or /etc). IT should be automatically created if it does not already exist. And this directory name should be overrideable from CLI flags.

For starters, we don't need the keyring or key file -- just server.toml.

We may also want/need a client.toml for configuring a Bindle client.

**Comment by technosophos** [comment]
- `server.toml` is done in #99
- `bindle create-key` does the logic for creating a signing key

So I think all that is left as of this writing is the public keyring

**Comment by thomastaylor312** [comment]
After the latest PR merges with keychain management from the CLI, I think this has been addressed
