### ISSUE TITLE
Server query doesn't seem to follow spec

### ISSUE THREAD

**Issue by itowlson** [deislabs/bindle#98]
The demo server has and bindle called `enterprise.com/warpcore` but if you query the demo server for `warpcore` it returns 0 results.

I thought this might be an old build but I cloned latest and seeded it with several bindles including `my/fancy/bindle` and `your/fancy/bindle` but querying for `fancy` still gave 0 results.

My reading of https://github.com/deislabs/bindle/blob/master/docs/protocol-spec.md#strict-mode is that substrings should match even in strict mode.  I don't know whether the issue is with the spec or the implementation though!

**Comment by itowlson** [comment]
Even an empty query seems to return 0 results even though I can successfully get the `enterprise.com/warpcore` bindle.

**Comment by technosophos** [comment]
I can reproduce:

```console
$ $(make client) search -q "warpcore"                      technosophos@HM-SB3202104
    Finished dev [unoptimized + debuginfo] target(s) in 0.30s
     Running `target/debug/bindle search -q warpcore`
[2021-04-15T03:03:35Z INFO  bindle::provider::file] Loading invoice 1927aefa8fdc8327499e918300e2e49ecb271321530cc5881fcd069ca8372dcd/invoice.toml into search index
query = "warpcore"
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []
```

**Comment by technosophos** [comment]
Further:

```console
$ bindle search -q enterprise.com/warpcore/1.0.0
[2021-04-15T03:38:47Z INFO  bindle::provider::file] Loading invoice 1927aefa8fdc8327499e918300e2e49ecb271321530cc5881fcd069ca8372dcd/invoice.toml into search index
query = "enterprise.com/warpcore/1.0.0"
strict = true
offset = 0
limit = 50
total = 0
more = false
yanked = false
invoices = []

```
